'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class CAISAExamenEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CAISAExamenEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Tbl_Usuarios() As DbSet(Of Tbl_Usuarios)
    Public Overridable Property Tbl_BitacoraContrasenia() As DbSet(Of Tbl_BitacoraContrasenia)

    Public Overridable Function spd_EliminarUsuario(idUsuario As Nullable(Of Integer)) As Integer
        Dim idUsuarioParameter As ObjectParameter = If(idUsuario.HasValue, New ObjectParameter("IdUsuario", idUsuario), New ObjectParameter("IdUsuario", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("spd_EliminarUsuario", idUsuarioParameter)
    End Function

    Public Overridable Function spi_InsertarUsuario(correo As String, usuario As String, password As String, nombre As String, apellidoPaterno As String, apellidoMaterno As String, fechaNacimiento As Nullable(Of Date), edad As Nullable(Of Integer), direccion As String, telefono As String) As Integer
        Dim correoParameter As ObjectParameter = If(correo IsNot Nothing, New ObjectParameter("Correo", correo), New ObjectParameter("Correo", GetType(String)))

        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(String)))

        Dim passwordParameter As ObjectParameter = If(password IsNot Nothing, New ObjectParameter("Password", password), New ObjectParameter("Password", GetType(String)))

        Dim nombreParameter As ObjectParameter = If(nombre IsNot Nothing, New ObjectParameter("Nombre", nombre), New ObjectParameter("Nombre", GetType(String)))

        Dim apellidoPaternoParameter As ObjectParameter = If(apellidoPaterno IsNot Nothing, New ObjectParameter("ApellidoPaterno", apellidoPaterno), New ObjectParameter("ApellidoPaterno", GetType(String)))

        Dim apellidoMaternoParameter As ObjectParameter = If(apellidoMaterno IsNot Nothing, New ObjectParameter("ApellidoMaterno", apellidoMaterno), New ObjectParameter("ApellidoMaterno", GetType(String)))

        Dim fechaNacimientoParameter As ObjectParameter = If(fechaNacimiento.HasValue, New ObjectParameter("FechaNacimiento", fechaNacimiento), New ObjectParameter("FechaNacimiento", GetType(Date)))

        Dim edadParameter As ObjectParameter = If(edad.HasValue, New ObjectParameter("Edad", edad), New ObjectParameter("Edad", GetType(Integer)))

        Dim direccionParameter As ObjectParameter = If(direccion IsNot Nothing, New ObjectParameter("Direccion", direccion), New ObjectParameter("Direccion", GetType(String)))

        Dim telefonoParameter As ObjectParameter = If(telefono IsNot Nothing, New ObjectParameter("Telefono", telefono), New ObjectParameter("Telefono", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("spi_InsertarUsuario", correoParameter, usuarioParameter, passwordParameter, nombreParameter, apellidoPaternoParameter, apellidoMaternoParameter, fechaNacimientoParameter, edadParameter, direccionParameter, telefonoParameter)
    End Function

    Public Overridable Function sps_ObtenerContraseniasPorUsuario(idUsuario As Nullable(Of Integer)) As ObjectResult(Of sps_ObtenerContraseniasPorUsuario_Result)
        Dim idUsuarioParameter As ObjectParameter = If(idUsuario.HasValue, New ObjectParameter("IdUsuario", idUsuario), New ObjectParameter("IdUsuario", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sps_ObtenerContraseniasPorUsuario_Result)("sps_ObtenerContraseniasPorUsuario", idUsuarioParameter)
    End Function

    Public Overridable Function sps_ObtenerUsuarioPorId(idUsuario As Nullable(Of Integer)) As ObjectResult(Of sps_ObtenerUsuarioPorId_Result)
        Dim idUsuarioParameter As ObjectParameter = If(idUsuario.HasValue, New ObjectParameter("IdUsuario", idUsuario), New ObjectParameter("IdUsuario", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sps_ObtenerUsuarioPorId_Result)("sps_ObtenerUsuarioPorId", idUsuarioParameter)
    End Function

    Public Overridable Function sps_ObtenerUsuarioPorUsuario(usuario As String) As ObjectResult(Of sps_ObtenerUsuarioPorUsuario_Result)
        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sps_ObtenerUsuarioPorUsuario_Result)("sps_ObtenerUsuarioPorUsuario", usuarioParameter)
    End Function

    Public Overridable Function sps_ObtenerUsuarios() As ObjectResult(Of sps_ObtenerUsuarios_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sps_ObtenerUsuarios_Result)("sps_ObtenerUsuarios")
    End Function

    Public Overridable Function spu_ActualizarContrasenia(idUsuario As String, password As String) As Integer
        Dim idUsuarioParameter As ObjectParameter = If(idUsuario IsNot Nothing, New ObjectParameter("IdUsuario", idUsuario), New ObjectParameter("IdUsuario", GetType(String)))

        Dim passwordParameter As ObjectParameter = If(password IsNot Nothing, New ObjectParameter("Password", password), New ObjectParameter("Password", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("spu_ActualizarContrasenia", idUsuarioParameter, passwordParameter)
    End Function

    Public Overridable Function spu_ActualizarUsuario(idUsuario As Nullable(Of Integer), correo As String, nombre As String, apellidoPaterno As String, apellidoMaterno As String, fechaNacimiento As Nullable(Of Date), edad As Nullable(Of Integer), direccion As String, telefono As String) As Integer
        Dim idUsuarioParameter As ObjectParameter = If(idUsuario.HasValue, New ObjectParameter("IdUsuario", idUsuario), New ObjectParameter("IdUsuario", GetType(Integer)))

        Dim correoParameter As ObjectParameter = If(correo IsNot Nothing, New ObjectParameter("Correo", correo), New ObjectParameter("Correo", GetType(String)))

        Dim nombreParameter As ObjectParameter = If(nombre IsNot Nothing, New ObjectParameter("Nombre", nombre), New ObjectParameter("Nombre", GetType(String)))

        Dim apellidoPaternoParameter As ObjectParameter = If(apellidoPaterno IsNot Nothing, New ObjectParameter("ApellidoPaterno", apellidoPaterno), New ObjectParameter("ApellidoPaterno", GetType(String)))

        Dim apellidoMaternoParameter As ObjectParameter = If(apellidoMaterno IsNot Nothing, New ObjectParameter("ApellidoMaterno", apellidoMaterno), New ObjectParameter("ApellidoMaterno", GetType(String)))

        Dim fechaNacimientoParameter As ObjectParameter = If(fechaNacimiento.HasValue, New ObjectParameter("FechaNacimiento", fechaNacimiento), New ObjectParameter("FechaNacimiento", GetType(Date)))

        Dim edadParameter As ObjectParameter = If(edad.HasValue, New ObjectParameter("Edad", edad), New ObjectParameter("Edad", GetType(Integer)))

        Dim direccionParameter As ObjectParameter = If(direccion IsNot Nothing, New ObjectParameter("Direccion", direccion), New ObjectParameter("Direccion", GetType(String)))

        Dim telefonoParameter As ObjectParameter = If(telefono IsNot Nothing, New ObjectParameter("Telefono", telefono), New ObjectParameter("Telefono", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("spu_ActualizarUsuario", idUsuarioParameter, correoParameter, nombreParameter, apellidoPaternoParameter, apellidoMaternoParameter, fechaNacimientoParameter, edadParameter, direccionParameter, telefonoParameter)
    End Function

End Class
